import {
  alignContent,
  AlignContentProps,
  alignItems,
  AlignItemsProps,
  alignSelf,
  AlignSelfProps,
  compose,
  display,
  DisplayProps,
  flex,
  flexBasis,
  FlexBasisProps,
  flexDirection,
  FlexDirectionProps,
  FlexProps,
  flexWrap,
  FlexWrapProps,
  justifyContent,
  JustifyContentProps,
  justifySelf,
  JustifySelfProps,
  order,
  OrderProps,
} from 'styled-system'

export interface FlexboxesProps
  extends AlignContentProps,
    AlignItemsProps,
    AlignSelfProps,
    DisplayProps,
    FlexBasisProps,
    FlexDirectionProps,
    FlexProps,
    FlexWrapProps,
    JustifyContentProps,
    JustifySelfProps,
    OrderProps {}

export const flexboxes = compose(
  alignContent,
  alignItems,
  alignSelf,
  display,
  flex,
  flexBasis,
  flexDirection,
  flexWrap,
  justifyContent,
  justifySelf,
  order,
)
